### ISSUE TITLE
Make test dependencies optional

### ISSUE THREAD

**Issue by Ambrevar** [mrosset/giqt#2]
Currently we need to have all deps for all test cases.  But the user is only interested in, say, Common Lisp, they don't need the dep on Guile, Python, etc.

What about removing the hard dependency on the tests and adding optional flags instead?

@jmercouris

**Comment by mrosset** [comment]
@Ambrevar I talked a bit about this on IRC with @jmercouris . At this time the guile dependencies are a hard requirement. Since any changes to the giqt could negatively impact both guile and sbcl code. I think though there is room for improvement. I'll do my best to clean this up today. But for something like MacOS which I don't have access to. It would be nice to know that the guile tests are passing too. In short it is hard to support giqt without knowing that all the tests are passing. And it allows me to fix any issues with MacOS that I could not find on my own accord. 

Let me know how important this feature is, and I will implement it. But it's added work that is just going to detract from other stuff I'm working on right now. Mainly the qt packages for guix.

**Comment by Ambrevar** [comment]
Hmm, maybe you misunderstood what I meant.

I suggested that we have a build chain for building the typelib even
when Guile et al. are not installed.  If I'm not mistaken, we only need
a C++ compiler, QtWebengine and GI to build the typelib.

This is a general suggestion, it's not related to macOS in particular.

Does that make sense?

**Comment by mrosset** [comment]
I do understand what you mean @Ambrevar . It's more of a timing/time factor on my end. giqt is not even alpha state at this point. And though ideally we'd like this to be pretty portable typelib. It's current state is pretty biased towards being used by nomad and next browser and there is no way we can have a complete QT API I'm just laying the ground work and added the basics needed by nomad and next. And so I rely heavily on the the sbcl and guile tests to ensure both are on par. That's why I only have tests for those and for posterity I have examples for python and javascript.  I intentionally added sbcl to ensure sbcl is on equal footing as guile. Keep in mind it's double the work/effort adding the sbcl tests. I could just use guile tests instead.

So I don't think it's to much to ask early adopters/developers to ensure the guile tests are passing on there OS/ARCH. Since it furthers the greater good as a whole. And the only reliable way to ensure the typelib is working it to use unit-tests where feasible. Especially this early in development. 

If push comes to shove, I can make this an elective but it's much sooner then I would have like to maybe do this. And I'd be much more confident doing it know the guile tests passed at least once on a new architect.

**Comment by Ambrevar** [comment]
The main issue here, I believe, is that Guile libraries are not very popular on many distros, which means that for most of users our there they will have to build guile-lib and g-golf manually.  I understand your point, but the reverse side of the coin is that GIQt is potentially losing people who could get the typelib to work for their language of choice. (Python, Javascript, SBCL, you name it.)
Even if users don't send feedback about Guile, they can still send feedback about the language they use, and that alone is valuable in my opinion.

**Comment by mrosset** [comment]
@Ambrevar  I have not forget about this issue. It's just lower on my priority list right now.

I will add this feature because technically you are right giqt is a typelib library. And it should probably be language agnostic.

But I also do not want to misled people into thinking this is full GI binding to QT. Since supporting something like would probably be a full time job unto it's self. 

I think I could go so far as state. GITQT supports a limited subset of QT and GI features. Enough to support what next and nomad need. If people would like add more features with tests I can support pull requests and patches.

**Comment by Ambrevar** [comment]
No problem.

Regarding the user expectations, I think it's fine (if not better?) to
be explicit and add a *big* warning in the README, stating that this is
not a complete binding.

**Comment by Ambrevar** [comment]
Nice, thanks!
